/**
 * The scope of a Dialect determines how its `pattern` is interpreted
 * during matching.
 *
 * - `'exact'`      — The pattern is compared verbatim (case-insensitive,
 *                    trimmed) against the raw bank description string.
 * - `'structural'` — The pattern is compared against the `searchKey`
 *                    generated by `MovementTokenizerService`, which replaces
 *                    variable segments (dates, IDs…) with typed placeholders
 *                    such as `{date}` and `{id}`.
 */
export type DialectScope = 'exact' | 'structural';

/**
 * A Dialect is a single bank-string pattern that maps to a Canonical Entity.
 *
 * The many-to-one relationship (many Dialects → one `ICanonicalEntity`) allows
 * the system to recognise different "surface forms" of the same real-world
 * payee.  For example, all of the following might be Dialects of "Continente":
 *
 *   exact      → "COMPRA CONTINENTE LDA"
 *   exact      → "DD CONTINENTE SA"
 *   structural → "trf {date} continente {id}"
 */
export interface IDialect {
  /** Auto-incremented primary key managed by Dexie. */
  id?: number;

  /**
   * Foreign key referencing `ICanonicalEntity.id`.
   * The persistence layer enforces cascade-delete: removing an entity
   * removes all of its dialects.
   */
  entityId: number;

  /**
   * The matching string for this dialect.
   * - When `scope === 'exact'`:      the raw bank description value.
   * - When `scope === 'structural'`: the `searchKey` produced by
   *   `MovementTokenizerService.generateSearchKey()`.
   */
  pattern: string;

  /**
   * How the `pattern` should be interpreted during lookup.
   * @see DialectScope
   */
  scope: DialectScope;

  /**
   * The header/column name this pattern was derived from (e.g. "Description",
   * "Descrição").  Used to restrict matching to the same field so that a
   * "Description"-scoped pattern is not accidentally applied to a date column.
   */
  sourceField: string;

  /**
   * Matching priority — higher numbers are evaluated first.
   * Dialects inherited from old rules default to `0`; user-created dialects
   * default to `1` so they take precedence over legacy data.
   */
  priority: number;

  /** Unix epoch timestamp (ms) when this dialect was first created. */
  createdAt: number;
}